import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

import { Header } from './components/layout/Header'
import { Footer } from './components/layout/Footer'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Reginaldo Gomes - Front-end developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='min-h-screen'>
      <body className='flex-col bg-secondary-500 text-base text-primary-300 font-primary p-2'>
        <Header />
        <main className='min-h-screen bg-primary-600 p-2 my-2 rounded'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
